# Generated by Django 3.2.13 on 2022-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusers',
            name='order_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
